### ISSUE TITLE
Add push notification about upcoming pickups

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1027]
UPDATE in https://github.com/yunity/karrot-frontend/issues/1027#issuecomment-487307579

---

From foodsharing Poland:

> push notifications in android app work quite well. for now, they are only displayed when someone writes a post. i think it would be great to introduce in the app the same notifications as we get now by email, like upcoming pickups or week summary. also, add option to manage push notification settings

I wonder what their use case is. We can only push little bits of unformatted information compared to emails that can contains lots of styled text.

I think mobile push notifications about joined and empty upcoming pickups make sense, but not the whole summary email.

**Comment by nicksellen** [comment]
Yes, seems reasonable to send out the evening picking notifications via push aswell, in a condensed text form.

Could also consider the individual pickup notifications, e.g. 2h before the pickup is due when no-one is signed up... emergency notifications!

**Comment by tiltec** [comment]
Maybe it would be a nice starter task to add pickup notifications to the app? Could either be implemented as push or as local notification (for example with [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications)).

**Comment by RobertKopczynski** [comment]
Hello, could I give a try?

**Comment by tiltec** [comment]
Hi @RobertKopczynski - sure!
Tell me what you need to know!

**Comment by CSBatchelor** [comment]
Hello, I've been looking for some issues to work on for my first Hacktoberfest and this project caught my interest. I see another developer claimed this back in May but it seems this issue has gone stale. Do you mind if I take a swing at it?

**Comment by RobertKopczynski** [comment]
Sure, I had something come up in May, just after picking it up and kinda
forgot about it.

I remember having problems with
https://github.com/katzer/cordova-plugin-local-notifications not working
for a emulator.
Something about getting some bizarre errors, that didn't show up for more
modern versions of Android.
For more modern Android versions, the emulator would start a test program
of the plugin, but most buttons didn't do anything? One button did
something but not a local notification.
Error messages did say something was missing/wrong? I did something that
made the message to go away, but it didn't fix local notification not
showing up.
I don't think I found ready-to-go solution/plugin and I was thinking about
making notifications from scratch. But then something unrelated came up.

I didn't check for iPhones, due to not owning one.

wt., 1 paź 2019 o 03:58 Christian Batchelor <notifications@github.com>
napisał(a):

**Comment by tiltec** [comment]
@CSBatchelor welcome! 
@RobertKopczynski thanks for the writeup!

https://github.com/katzer/cordova-plugin-local-notifications seems maintained, so maybe it's worth checking if the mentioned problems still exist and if yes, ask for support.

Of course it's also possible to implement this as push notification via the existing FCM infrastructure - then you need to add the code in [the backend](https://github.com/yunity/karrot-backend/blob/master/karrot/subscriptions/tasks.py)

**Comment by nicksellen** [comment]
I only just noticed your assignment @tiltec so hopefully I didn't implement something when you had a draft in progress too...

**Comment by tiltec** [comment]
Nope, might have assigned myself on mistake!
