### ISSUE TITLE
[Feature Request] Add possibility to sign up for recurrent pickups

### ISSUE THREAD

**Issue by mitjanikolaus** [yunity/karrot-frontend#1035]
It would be nice to have the option for end users to join pickups recurrently. For example, I know that I will do one specific pickup every Tuesday. Most of our volunteers have such regular shifts so it would be nice if they would only have to interact with the system if something changes about their regular shifts.

**Comment by tiltec** [comment]
Indeed that seems like a feature we should consider now. 

foodsharing.de has this feature as well, but I decided not to copy it when I started karrot development. From my perspective, it wasn't used widely. Where it was used, it made the pickups less friendly for newcomers, because they are already taken by someone.
As upside, I can see that recurring pickups done by the same people, increase the stability of a foodsaving group.

So from my perspective, I'm happy to accept Pull Requests for this! I wouldn't make it a priority though because there are other more pressing issues.

**Comment by djahnie** [comment]
Just out of interest, what foodsaving group are you requesting this for, @mitjanikolaus?

**Comment by mitjanikolaus** [comment]
I am asking for de Voedselkringloop in Amsterdam.
Regarding the issue with newcomers: I think it is always good to have the option for additional people to join pickups even if there is already a person doing it. Like this newcomers can easily be integrated :)

**Comment by DougInAMug** [comment]
Bump: For Foodsharing Edinburgh, this would be a significant improvement. All of their stores are coordinated/picked-up by the same person(s). Not having this feature would mean a lot of work for them if they wanted to start using Karrot.

(Further to the Foodsharing Edinburgh meeting I attended 2018-07-02)

**Comment by nicksellen** [comment]
Thanks!

The main hesitation here is to avoid the scenario where the same people "block" certain pickups forever preventing other people from doing them.

One way to solve this would be to only allow recurring collectors _if_ you also have some other slots available for non-recurring collectors - which fits in nicely with the idea from @mitjanikolaus.

Any thoughts?

**Comment by guidocalvano** [comment]
@nicksellen I might have a different approach to tackle your problem (though I don't know yet how difficult it might be to build or if it makes sense); 

Allow new volunteers to assign themselves to a pickup that has been permanently assigned. If this happens the recurrent assignee gets an email informing them that a new volunteer has taken over their shift. The change could happen automatically or we could ask an ok from the original assignee. 

To prevent problems of two people heading to the same pickup this might only be allowed x days in advance. This prevents the system from saying no to someone who enthusiastically wants to take a recurring pickup, without shutting out new comers.

**Comment by djahnie** [comment]
I like that idea, @guidocalvano! Another way of implementing it could also be that a permanently assigned pickup always has an extra slot, so that a potential new collector automatically enters the pickup chat with the old collector, when signing up. This way both can then converse to find out if it makes sense to go together, if the old one has any resistance to letting the new one take over, or if there's anything else that needs to be kept in mind. No idea how complicated this would be to code though... ;)

**Comment by tiltec** [comment]
Hi @mitjanikolaus @guidocalvano - are you still interested in having this feature? Are you using some workaround currently?

**Comment by mitjanikolaus** [comment]
At the moment we are not using karrot, also because this feature is missing.

**Comment by tiltec** [comment]
This sounds like there are other, perhaps bigger, things missing in Karrot for the use case of your group. If you're still interested, we could have a call or a chat.

**Comment by tiltec** [comment]
We had a brief discussion about this right now and it seems the main reason to implement this seems to be if you want to use the feedback feature of Karrot, but avoid that the user has to visit Karrot before the pickup happens and click a button. This is not how most groups use Karrot, so it wouldn't be a benefit for them. 
If you really want this feature, we need help from your side to implement it. Please comment, then I'll open the issue again!
