### ISSUE TITLE
Preview pickup chat

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1046]
Bruno from Solikyl said:

> A friend of mine using Karrot here also suggested to me, when I commented the new [pickup chat] feature, that the chat should be open for others to read at least before joining the pickup, so other people would see how what is being discussed and feel motivated to join. I'm still unsure whether that's a good option or not

It would be a bit like slack channel previews - and the user would not become part of the chat, but just have read-only view of the chat.

**Comment by brnsolikyl** [comment]
I think it's useful and could have been useful in many occasions, and for the moment I do not see a reason why it should not be open for others to read. We might even consider in the future making it open for others to participate in, but we'd need more feedback and that's for later IMO. I myself joined a  pickup these days just to leave a very important message to those who would be doing the pickup, and left the pickup right away because I could not be present. However, this scenario would probably not happen again if we have store conversations and subscriptions

**Comment by tiltec** [comment]
Thanks! I have the feeling it makes sense to think about this in the context of store conversations & subscriptions, so I'll close this in favor of #986
