### ISSUE TITLE
Add conversations overview

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1070]
At the moment you can have conversations in the following places:
- on a group wall
- in a group wall thread
- on a pickup
- in a private chat with another user

But there is nowhere that shows you how many unread messages you have overall, and how to navigate to those places. It is very easy to miss messages at the moment.

The idea would be to have a conversation overview page where you can see the conversations, and navigate to them, additionally to have some status on the page somewhere that lets you know there are unread messages (e.g. in the topbar).

This might have some backend implications too, but maybe not also.

At the moment there is a conversations endpoint to list them all, and they should get a websocket update whenever they join/leave a conversation, and when the information changes (e.g. unread message count).

Currently the conversations store module does not hold all of these conversations, as it aims to only keep information for the active one on the page (and it's messages). One approach would be to have a seperate store module just for handling unread message notifications, and the conversation summaries so as not to further complicate the conversations store module.

**Comment by nicksellen** [comment]
What about the group wall threads? They do normally go in a detail sidebar, maybe it makes sense to include them too, not sure.

But I agree about wall messages themselves, they don't seem to quite belong in a conversation overview.... but it would be nice to have the unread message notifications for walls/threads somewhere.

**Comment by tiltec** [comment]
I'd put the most recent group wall threads, where the user is participant, on the conversations page too.

What do you think about filtering conversations by their associated group when possible, to show only pickup chats, application chats and replies that belong to the current group? Private chats would all be shown.

**Comment by tiltec** [comment]
JSON response for `GET /api/conversations/` looks like this after some changes. I added `type` and `latest_message`. The list is sorted by `latest_massage.created_at` - quite some stress for the database, but seems to be ok for now (later the latest message could get stored in the conversations model).

`type` can be one of: `private`, `pickup`, `group`, `application` or None, but the latter shouldn't happen in production code.

The result is paginated, with a simple page number for now. Cursor pagination wouldn't work because it wants to impose its own ordering and can't use relations for ordering.

```json
[
    {
      "id": 274,
      "participants": [
        12,
        58
      ],
      "updated_at": "2018-08-03T21:39:00.376520Z",
      "seen_up_to": 133,
      "unread_message_count": 0,
      "email_notifications": true,
      "latest_message": {
        "id": 321,
        "author": 12,
        "content": "ajskldfajsfd",
        "conversation": 274,
        "created_at": "2018-08-03T21:39:08.221259Z",
        "updated_at": "2018-08-03T21:39:08.221687Z",
        "reactions": [],
        "received_via": "",
        "is_editable": false,
        "thread": null,
        "thread_meta": null
      },
      "type": "pickup"
    }
]
```

I guess I should add a filter by type, too. Or at least exclude the "group" conversation.


The **thread response** didn't change so much as I didn't manage to include the latest message yet - the ConversationMessage object references itself and it became quite fiddly with recursive queries and recursive serializers. I added a `my_threads` query parameter, which changes the sorting to latest message and only returns threads where `request.user` is in.

`GET /api/messages/?my_threads=1`

But I think the CursorPagination overrides my ordering, so I need to use page numbers too.
