### ISSUE TITLE
Rationalize frontend messages store

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1091]
The frontend messages store got a bit disorganized lately, with three vuex modules containing conversations and messages: `conversations`, `currentThread` and `latestMessages`.

- conversations: wall messages, detail sidebar (but not threads)
- currentThread: thread sidebar
- latestMessages: messages popover and page, unreadCount for various bits around Karrot

Problems as of now:
- data needs to be updated in multiple places
- conversations module is tightly coupled to currentThread module
- isUnread status is wrong for thread replies when no currentThread is selected

I guess at this stage it makes sense to rethink messages storage.

**Comment by nicksellen** [comment]
> data needs to be updated in multiple places

I wouldn't consider this a problem, I think it's quite natural that some of the store module state is denormalized. I would like it if vuex gave an option to have global mutations when using namespaced modules (such that you can commit a change, and multiple modules can receive the mutation and update their state as appropriate) - which we could implement ourselves if it seems a good way forward.

> conversations module is tightly coupled to currentThread module

The global mutations pattern could help with this too. An extension of the idea would be to slightly seperate "read" (getters) and "write" (actions) steps - so we might trigger all conversation-related actions in a conversations module (that does not keep (much) state), but let other modules receive the mutations in order to manage the state in a more specific way.

I would also consider it in the context of https://github.com/yunity/karrot-frontend/issues/1066 (<-- ooh 1066 is the date of the Battle of Hastings)

**Comment by tiltec** [comment]
I moved this into the "Current Development" milestone to have it as part of the _Refactoring winter_ ;)

**Comment by tiltec** [comment]
I tried some approaches, unsuccessfully. Seems still ok how it is right now, so I would close again.
