### ISSUE TITLE
Group customization options

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1259]
Based on #676 

Latest discussion favors group customization options over site customization (to allow one deployment to be used for different groups, shared login).

We already support a group logo. @nicksellen played with color/background customization and his preliminary conclusion was "predefined themes" to keep some control over usability concerns (e.g. prevent some group from making horrible myspace themes).

There was also the idea of enabling/disabling certain features per group, e.g. feedback. Related is also the [Tag system for pickups](https://community.foodsaving.world/t/tag-system-for-events-pickups/206), which might bring us group-defined or pre-defined categories.

**Comment by brnsolikyl** [comment]
For the Bike Kitchen project specifically, more customization would entail:
* rename pickups to "opening shifts" or something similar. Even the more general "activities" or "events" could work even better
* replace food basket and shopping cart icons for bike related ones
* rename stores to "Bike Kitchens and Bike Pickups" (ideally separating the places into types, as we discussed in the topic of generalization). 
* change store status to "active", "idle", "inactive" and newly created. Question: could we play here and use status as types, to distinguish between Bike Kitchens and bike pickups?
* leave the feedback feature with the comment field alone, taking away the amount of food saved. Or just take away the feature completely from the UI.
* change the background image to one related to bikes

I'm also in favour of a more general approach (hard to call it customization, right?) even for the Bike Kitchen case:
* rename Pickups to Activities or Events
* rename Stores to Places
* change food-related icons to other less specific ones, related to place and activity
* change store status to "active", "idle", "inactive" and "newly created"
* Feedback feature only with the comment field
* change the background image to something else

**Comment by djahnie** [comment]
Thanks @brnsolikyl for pointing out these very specific points! To cater to them we'd need group types like 'foodsaving group' and 'bike kitchen group', which would go into the exact opposite direction of general customization, I'd say. I see general customization more like an option to change names and pictures and things like that in the group settings.

If we talk about the more general approach this is not about 'Group customization options' indeed, but since we're here now anyways, let's just do it...^^
And I think this is the way we all prefer right now, so I'm happy to go into more detail on the individual points.

> rename Pickups to Activities or Events

There already is an issue for this one here: #1127 
It has higher priority but since it's quite a big change it will take some time. Maybe we can take some shortcuts but it will be ugly...

> rename Stores to Places

There is a pull request here: #1398 
It's basically ready, but we need to find out how other groups like it. Tilmann already started writing a forum post but then the hands happened. We'll resume this very soon!

> change food-related icons to other less specific ones, related to place and activity

In the above-mentioned PR the shopping cart icon is already replaced by [dot circle](https://fontawesome.com/icons/dot-circle?style=regular). What other icons would you like to see changed and do you have ideas for this?

> change store status to "active", "idle", "inactive" and "newly created"

So that would mean to change:
- "cooperating" to "active"
- "negotiating" to "idle"
- "don't want to cooperate" to "inactive"
- and "just created" to "newly created"

Right?

>  Feedback feature only with the comment field

It would be bad for the foodsaving groups to completely remove the weight estimations, but I think we already talked about the option to have different store types or pickup types with different feedback options. This is also discussed in #1127. There is still no clear solution agreed upon, so it might take some time.

> change the background image to something else

I just found out that Tilmann apparently prefers the option to have a set of pictures available and not let users upload any picture they want and set it as background for the group... So much for my idea of 'general customization'... :sweat_smile: :open_mouth: :smile: 
To the reasons: Not any picture makes sense as a background; size, color scheme and pattern need to fit to ensure readability and a somewhat smooth layout. If those things are not a given it might be interpreted as the software's fault - and we don't want that...
So we could make a collection of suitable background images like the one we have a right now, the bike kitchen pic you had in your mock-up and something super neutral. And potentially more in the future. The very first implementation wouldn't even have a button in the UI, but we could just set the bike kitchen's background picture. What do you think?

**Comment by djahnie** [comment]
One more clarifying question about your point here:

> change store status to "active", "idle", "inactive" and newly created. Question: could we play here and use status as types, to distinguish between Bike Kitchens and bike pickups?

What exactly do you have in mind there? I mean, you can always use status and interpret it as whatever you want, but I somehow guess that's not what you're talking about..?
Additionally, stores that are set to anything else as 'active' are by default not shown in the sidenav and the toggle button only separates between 'active' and 'active and everything else'.

**Comment by brnsolikyl** [comment]
Thanks for the meeting we had today  @djahnie ! I think you defined very well what I'm suggesting on the meeting notes, and I'll write it here again just for the record: pre-defined themes for groups, foodsaving being the default one. We'd add a Bike Kitchen theme and also a neutral one. I think it's probably better if I open another issue to discuss the BK theme more specifically and the changes it would entail, and also answer the points you raised more specifically (more for the record again, since I think we already covered much of it on the meeting :laughing: ). I'll do that on Tuesday evening after I meet Sebastian.

**Comment by tiltec** [comment]
We now have 'group theme' support, but it's very basic (no translation support, no backend support). If the current feature seems useful to groups, we should implement it in a proper way. Otherwise, I'd think it would be good to remove it again in a year or so, to reduce confusion.
