### ISSUE TITLE
Add better notifications settings page

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1457]
As of https://community.foodsaving.world/t/improving-notifications-and-ux-draft/227

According to usability tests, we need a better notifications settings page.

**Comment by tiltec** [comment]
Notification page has been moved into settings. Next steps would be:
- add button to unsubscribe from all notification emails; per group)
- add button to unsubscribe from group wall, store walls, pickup chats, application chats, issue chats, etc; one button per type, needs backend+frontend
- add button to control private message notifications; _not_ per group, maybe show a hint inside a private chat when notifications have been disabled: "this user has turned off notifications, your message might not be seen in time"; needs backend+frontend
- add bell notification settings per type; some types grouped to one setting; needs backend+frontend

**Comment by tiltec** [comment]
Some more details (from a meeting with @djahnie):
- expose API to "unsubscribe all notifications for a group", similar to the logged-out one
  - exceptions: account emails, own applications, inactivity reminders, own conflict resolution, …?
- add stats for logged-out actions, to find out if people use them
- add mute option to each private chat
  - add hint for conversation partner
- think about decoupling email and push settings; push settings should only be configured for the current client (i.e. android app shouldn't disable browser push)
- add API to toggle frequent bell notifications; most frequent ones can be found in grafana

**Comment by brnsolikyl** [comment]
I see the "Unsubscribe All" button already in production and wonder if this will unsubscribe even from future conversations.

I had the following case just recently: A guy from the Bike Kitchen group did not want to receive e-mail anymore, so he went into the settings page and ticked off all of the options (I did not ask him about the "unsubscribe all" button because I haven't noticed until now). He was still getting e-mail, and then I realized it was because he had marked a place as favourite, so I told him just to unfavourite it and so it was solved.

I don't know if things could be more intuitive. If the unsubscribe all button does also unsubscribe from messages on favourite places and for future conversations, then I guess it's enough.

I wonder if the big bell icon to set notification for individual walls and chats could be improved/changed. So far I haven't seen people being very aware of its purpose. But I'd need to ask around more.

**Comment by tiltec** [comment]
"Unsubscribe all" is a one-time action that finds all conversations in a group and unsubscribes from them - it does not prevent subscribing to a conversation again.

The case you mentioned should be covered though: "unsubscribe all" will remove the subscription to the conversation of the favorited place. If the user however posts in that conversation afterwards, they will be subscribed again - if they don't want to receive emails about new mesages in the conversation, they need to mute it with the "bell toggle" (set to "some").

The reason for subscribing again is that it would be surprising to not get any notification about new messages after posting one yourself.

We could make the logic more complicated and add a "disable emails" setting that prevents message notification emails from getting sent, no matter what the subscription setting is. Maybe that's worth it...

For reference, here's the unsubscribe logic: https://github.com/yunity/karrot-backend/blob/b34954640f9bb5765c6a8442ddf3bfc91886d751/karrot/unsubscribe/utils.py#L72

**Comment by brnsolikyl** [comment]
Thx for the quick answer! I was just writing about an option to include on the settings page a box for all conversations and replies, which would make only app/website notifications on by default, future and past. I think it's a good feature to have.

**Comment by tiltec** [comment]
Weekly stats:

![image](https://user-images.githubusercontent.com/4410802/68692273-7c1fe900-0575-11ea-91e3-0b546ede1982.png)

We most send out group notification messages, followed by pickup notifications.

**Comment by brnsolikyl** [comment]
I think this has been addressed too.
