### ISSUE TITLE
Keep message drafts

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1459]
It's quite easy to lose message drafts on Karrot. Typical causes might be page reloads and components getting temporarily destroyed  (`v-if`). It would be useful to have a "message drafts" concept.

It could be saved in local storage or synchronized to the server. Drafts should be saved for each user and conversation, maybe also when a message gets edited.

**Comment by Gerald1614** [comment]
Hi, i am not sure it correspond 100% to the initial ask, but I could use localStorage to keep the content of the message.  I delete it only if the user press escape, submit the form or leave voluntary the page. but on a page refresh, the content of the draft will be included in the input of the message. I use local Storage because my feeling is that this feature is mainly useful to maintain continuity of user experience when they are inside a specific session. There are not many reasons to maintain the state of a draft across different devices. I guess that at this stage a use would understand he would lose his draft.  it could be done but I personally it would generate backend logic unnecessarily. let me know if you want to exchange on this capability and see the 6 lines of code I had to produce to address that to see if he code does the job or if you would prefer to get different behavior. thanks

**Comment by tiltec** [comment]
Hi, thanks for looking into this! Sure, I'm happy about a localStorage solution too. Can you open the Pull Request?

**Comment by Gerald1614** [comment]
HI, I will. But i have a question. in fact when i go to pickups, we can comment on all pickup dates. when refreshing the web browser the detailsliderbar that contains the conversationCompose disappears. The n the local storage value gets used even if I click on another pickup date. I could instead of saving a single key value pair save an object with the draft and the groupId, placeId and pickup date. in such case I could make it clean but I think it would not be the right thing to do. we should just repvent the detailsliderbar to disappear on page refresh. in such case, the thnigs I build would work as only volunteer exit of this forms would delete the draft. (escape, submit or move to another page). what is exactly the behavior you expect. I could look at why the detailsliderbar disappears on page refresh and try to correct it at the same time. let me know

**Comment by tiltec** [comment]
I think it should keep the draft even when the sidebar is closed or another one gets opened.
Every conversation has a unique id, you could use that to store message drafts (instead of groupId, placeId, etc).

You might need a special handling for editing message that already have been sent, maybe it's ok to not keep drafts of the edited text.

**Comment by tiltec** [comment]
To make the sidebar persistent, we need to reflect the "sidebar open" state in the URL and change the layout to make it possible. I already did this for the "Issues" feature, but it's quite some work and easy to break something. So better leave that for later and do it in a separate PR.
(Of course you could also do it in localStorage, but I strongly think the URL should reflect the page you are viewing.)

**Comment by Gerald1614** [comment]
ok. i understand, i need to work now, but I will look at it later today and come back to you

**Comment by Gerald1614** [comment]
> I think it should keep the draft even when the sidebar is closed or another one gets opened.
> Every conversation has a unique id, you could use that to store message drafts (instead of groupId, placeId, etc).
> 
> You might need a special handling for editing message that already have been sent, maybe it's ok to not keep drafts of the edited text.

when the message is submitted i delete the local store, so the message is only kept if the user did not volunteraly submitted the message or quited the process (escape or move somewhere else)

**Comment by Gerald1614** [comment]
and also i thought abotu groupId and placeId because they are on the route. I agree 100% the conversationId should be part of the route parameters.

**Comment by Gerald1614** [comment]
done, but I do not have time now to send the PR. I will do it later. what i did was adding the conversationid as a prop and use it as a Key in localstorage. this is valid in pickups. on the wall conversation, i just create a 'wallConv" key. we would need to decide if there are other places to manage and as well. I will send the PR as soon as I can so you can review. it will be easier to tune it from there. rgds, gerald
