### ISSUE TITLE
Improve group invitations by link

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1559]
Bruno had a group for a specific event and spread the link to the groupPreview for people to sign up to Karrot and then join the group. Shorty after we had a confused Swedish speaking person in the playground group. Bruno clarified as follows:

> I believe he was looking for the new megaloppis group we created and there's a usability issue there that a friend of mine pointed out: we posted the link to the group for people to join but after signing up and confirming the e-mail address the person is not automatically led to the group intended for application

Todo: Create a link that makes it possible for people to sign up to Karrot for a specific group.

**Comment by nicksellen** [comment]
Clarification: this is not about the "invite by email" feature flow, but the general "signup and apply to group" flow.

**Comment by tiltec** [comment]
I guess this should be about a more straightforward way to send somebody the link to a group preview page and make sure they join exactly this group. I think we already have something in place that's called `joinGroupAfterLogin`, which should work after signup as well. But it might be that something gets lost on the way and it's not visible to the user what happens anyway, so there's plenty of room for improvements!

**Comment by nicksellen** [comment]
Yup, I went through the flow myself:

* I'm signed out and not registered
* visit group preview - https://dev.karrot.world/#/groupPreview/1
* click login or signup
* click signup
* sign up (leaving "join playground group" ticked)
* I'm signed up and sent back to group gallery
* select group again
* it tells me need to verify my email address...
* go to email and click the veritifcation link
* I'm verified and there is a "take me home" button
* back on group gallery again
* I select the group (3rd time now!)
* now I can apply

(_aside_: in the application chat I can't see the user names of the people chatting to me (they show as a ?) - the ? is a link though, with the id, and when I click it I can view the name of the person, 
... so it seems it would be nice to show the users name instead of ?)

so, from the above steps there are a few places to remember the group was selected:
* after signing up, should go back to the previously selected group, not the gallery
* after clicking verification link, should have a link/button to go to the group that was previously selected

I'm not sure exactly what should remember this group, it could all just be in the client, and maybe with some localStorage/persistedState to keep it around, or could get passed through to the backend (but seems harder, and not really needed).
