### ISSUE TITLE
Users can enter how much food they saved (feedback)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#159]
After doing the pickup, users can give a feedback:

- kilograms
- text field for comments

Should be separate for every user that participated in the pickup. Could be counted and used as statistics.

**Comment by D0nPiano** [comment]
I like the idea. Maybe there could be something reminder-ish / bells / popup, that appears the next time you are online after a pickup is done?

**Comment by djahnie** [comment]
Sounds nice!
Even though people probably tend to exaggerate a bit, when asked to enter the weight themselves each time. ;)
Some stats are definitely good for motivation! (Even Tais said it worked on her on foodsharing.de...^^)

**Comment by djahnie** [comment]
The data structure in [yunity/foodsaving-backend#253](https://github.com/yunity/foodsaving-backend/issues/253) lets every user who took part in a pick-up enter a comment and weight. 
So when entering the weight, should the users just estimate what _they themselves_ carried away or the weight of the complete pick-up? I guess it's the latter, so we should tell them somewhere to avoid confusion.
Another thing: Should we noticably limit the amount of characters in the comment fields, to force people to give concise feedback (like e.g. 100 characters max) or allow for verbose narratives?

**Comment by brnsolikyl** [comment]
I've been thinking about this issue here in our group and what I wanted to do regarding weight statistic is the same thing as Foodsharing.de did. Kristjan said the amount of food saved is based on an average that you take from weighing a limited number of pickups, say 10, and then you multiply this average by the total number of pickups. It seems much more reasonable than second-guessing the weight of each and every pickup.

It's a tough question, ideally we'd like to know more exactly the amount of food saved in each pickup and expect that foodsavers will be able to give this input. I'm a bit skeptical about it, but we could test it and see how people react to it. In my opinion I think the statistics https://github.com/yunity/foodsaving-frontend/issues/355 should be prioritized over this one. Then we'd be able to go back in history to see the total number of pickups and present the amount of food saved based on an average.

**Comment by tiltec** [comment]
The weight estimates on foodsharing are far off the truth. I did it myself when I was team leader in Munich, setting the weight to the upper limit that was expect. I did save tons of food, but the website showed easily double the amount.

As a base for the total amount of saved food per store, I would do the following:
- collect feedback from people who actually picked up
- calculate the average
- multiply the average with the total amount of pickups

This way every feedback contributes to the average, but feedback is not required to get weight added. In the long run, it should average out. In the even longer run, we could add a sliding window to the averaging function to put less weight on ancient feedback. That's a topic for future issues however.

#355 could be implemented with the current data already, while this issue is about collecting more data to make the statistics more accurate. I would be in favour of not showing bullshit statistics on foodsaving.world ;)

**Comment by brnsolikyl** [comment]
Calculating an average out of this feedback is a good way to go! I had understood, wrongly, that every feedback would just add on to the other.

In this case, I'm all for it!

**Comment by tiltec** [comment]
Ok, to the more technical matters:

The frontend needs to

1. show users when they can give feedback
2. collect the feedback and send it to the backend
3. get all feedback per store
4. get statistics derived from feedback weight

I would first implement points (2) and (3), where @id-gue and @mddemarie will work on the backend side.

**Comment by D0nPiano** [comment]
@tiltec what would be the best way of getting the information for 1.? Getting the data from the server while loading the pickupList and display a message at the top of the pickupList to give feedback?
Or have a request from topbar to a notifications service that checks for new feedback options, and display it in a bell-dropdown menu?

In the future, I think having a notifications endpoint in our backend would be best. Then our topbar could load `/api/notifications/` which could return something like
```
[{
id: 1,
type: PICKUP_FEEDBACK,
data: {pickupId = 1}
}]
```

**Comment by tiltec** [comment]
I agree that having an notifications endpoint makes sense from now on. There's an issue about notifications, isn't it?

**Comment by D0nPiano** [comment]
@tiltec  I don't think so - or at least I couldn't find it neither in backend nor in frontend.

**Comment by tiltec** [comment]
Should the weight be about the _whole_ pick-up or just the amount that the foodsaver took home?
It becomes relevant when calculating statistics.

Reasons for asking for the weight ...

(1) of the whole pick-up:

- maybe some people have better overview/are better at estimating
- if multiple users give feedback for the same pick-up event, we could calculate the average

(2) only of the amount the foodsaver took home

- it seems easier to estimate smaller amounts, which might give more accurate statistics
- conflicting feedback about the total amount are avoided

Anything else to consider?

I also thought about providing some estimation help on the website, i.e. displaying an image of a supermarket box and giving typical amounts if the box is filled with light/medium/heavy stuff. Obviously this will bias the statistics ;)

**Comment by D0nPiano** [comment]
Maybe we could just use little images and multiply these by the number of kilograms. Example:
Drawing apple and showing one for 200g, two for 400g and so forth. And if the user enters more than 4kg, we just display something else (melons, flour-packages, something heavy...)

I think (1) is also easier to explain - for scenarios like "I didn't take it home, but brought it to the next distribution point "Fairteiler" etc.), and might also be more accurate in the long run, because you always have multiple "votes" (you could even see who is under-/overestimating usually)

**Comment by tiltec** [comment]
Yes, the point about (1) being more simple makes sense to me. I also thought that we could offer both options to give feedback, but I feel that it would be unnecessarily complex, both to explain and to calculate the statistics.

**Comment by djahnie** [comment]
I also think that (1) is easier understandable and due to the possibility of calculating averages more exact.

Displaying examples sounds like a good idea to me. Do you imagine the pictures being shown _after_ the user entered the weight, @D0nPiano? If so, I guess it makes sense to directly offer the possibility to adjust the weight, in case the user realizes that judging by the picture the first estimation was way off, right?

**Comment by tiltec** [comment]
Since we started working on it, I will lift it to current development. Means that this has priority :)

**Comment by brnsolikyl** [comment]
I can see everyone here favored option (1): asking the total amount of food saved on a particular pickup and then calculating the average from each feedback. That's good, our foodsaving group usually leaves most of the food at a sharing point so this approach also makes sense to us. However, the beta version still asks how much the foodsaver "took home". So, this is just a reminder to rephrase the question, that is, change from "how much did you took home?" to "how much food was saved on this pickup?" (or similar).

**Comment by tiltec** [comment]
This won't make it into Release 4 probably, the backend has some open issues and the frontend UI is not fully implemented yet.

Need to figure out the current status and create a list of tasks.

**Comment by tiltec** [comment]
- [ ] show done pickups that the user can give feedback to (maybe in wall), needs backend implementation

**Comment by nicco11a** [comment]
I just noticed that we can leave feedback in Karrot about the weight and I like it, but 70 kilos is not enough. Yesterday I had 6 banana boxes and 2 bags of bread on our 3 wheel loading bike. It's max weight to carry is just 100 kilos + driver and I was probably towards 150 kilos or so on it..
http://www.nihola.com/products/family.html

and then we had another 70 kilos or so on a bike carriage.. and on Friday when we fetch things with a car from a relief organisation we fill a van for one place and several cars full with food so how about going a bit higher? 300 or 500 kilos perhaps?

**Comment by nicco11a** [comment]
I've asked for feedback on how much kilos a fully loaded van with food can take, will get back to you soon with a number.

**Comment by tiltec** [comment]
Agree, the weight input should not be limited at all.

**Comment by djahnie** [comment]
This probably is a minor concern, but if the weight input is unlimited what determines the pointer at the scale? I guess we just set arbitrary values? Like e.g. everything over 100kg has the pointer at maximum and the other orientations derive from that..?

**Comment by nicco11a** [comment]
Well, the scale could have a max, but just make sure there is a input field that we can put digits into and we are all set.

**Comment by tiltec** [comment]
I will close this issue now as the basics are implemented - refinements and elaborate statistics are still missing, as well as better notifications.
For more requests, please open a new issue.
