### ISSUE TITLE
User names can be missing in application chats

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1941]
As reported by @nicksellen in https://github.com/yunity/karrot-frontend/issues/1559#issuecomment-563365674, the applicant might just see `?` instead of user names. There is some code in place to prevent this (inside `latestMessages`), but it doesn't cover all cases.

**Comment by jasmlau** [comment]
Me and @allibail would like to claim this issue!

**Comment by jasmlau** [comment]
@tiltec Do you have any advice on how to start?

**Comment by tiltec** [comment]
Hi @jasmlau I'd love to help but I'm not very concentrated on computer work lately. Maybe @nicksellen is motivated to dive into this?

To get started, could you actually reproduce the problem yourself?

**Comment by allibail** [comment]
I am able to run the dev server and go to the pages specified in #1559. I can see users with correct usernames and users with "?" as their username in the chat. It looks like the "?" only appears for deactivated users, not all users, which is different from the behavior in the comment. Is this intentional or part of the bug?

**Comment by tiltec** [comment]
Users who left the group will also show `?`, but that's not part of this bug. Did you apply to join a group? Ideally, you should leave all other groups before.
