### ISSUE TITLE
Joining activity on Iphone requires two tapings before getting confirmation dialog

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#2257]
I've heard that someone had this problem in our group and now I tested on an Iphone 7 on Safari iOS 14.1

Normal behavior to join an activity is to tap once and then get the dialog to confirm. In this case you need to tap twice: on the first you'll see your avatar, and only on the second you get the dialog to confirm. 

![karrot-joining-pickup-iphone](https://user-images.githubusercontent.com/25367304/100796352-ca25ba00-3420-11eb-8c51-cf8692fe56ce.gif)

**Comment by nicksellen** [comment]
Seems it's _kind of_ intentional from apple

From [this article](https://css-tricks.com/annoying-mobile-double-tap-link-issue/) (well, from the article _it_ quotes):

> This is where the people at Apple might have been a bit too smart. They realized that there was a lot of functionality on the web relying on hover states and so they figured out a way to deal with that in Safari for iOS. When you touch an item on a webpage, it first triggers a hover state and then triggers the “click”. The end result is that you end up seeing styles applied using :hover for a second before the click interaction happens. It’s a little startling, but it does work. So Safari on iOS very much cares about your styles that have :hover in the selector. They aren’t simply ignored.

So, seems because we have that hover state (showing the profile picture as you hover), apple decided to make that occur on first click, then do the real click on the second click.

Seems like we could wrap the hover state in [this media query](https://drafts.csswg.org/mediaqueries/#hover)...

**Comment by brnsolikyl** [comment]
Aha!

**Comment by nicksellen** [comment]
Checkout PR which has a deployment URL for testing the fix :)

**Comment by brnsolikyl** [comment]
Great! Wlll test it tomorrow when I have the Iphone again at my disposal
