### ISSUE TITLE
ics download includes old activities

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#2428]
I used the lovely new button to download an ics file with the activities in on dev.karrot.world and it took ages then gave me a 1.1mb file with all the activities back to 2017 :)

https://dev.karrot.world/api/activities/ics/?group=6 was the URL.

I guess we want to only have current/future activities? Is there any case where old activities would be needed?

I don't know if this should be done on the backend or frontend, if the backend has a date filter param, maybe simplest to do in the frontend.

(I didn't try the ics subscription, maybe it is the same?)

**Comment by tiltec** [comment]
ping @amengsk - I think we only want future (and ongoing) activities by default?

**Comment by amengsk** [comment]
yes that is a problem i wanted to address

but as a calendar subscriber i would find it weird if yesterday's activity disappears from my calendar, too. so maybe the ics feed should also include activities which are (say) up to a month old, for instance?

intuitively i would just add the filter in the backend without needing to change any urls, so that the subscription urls remain simple. i would see it as a way for the backend to protect itself from expensive requests (hence not user-configurable)

**Comment by nicksellen** [comment]
Sounds good. I also assumed it would just have the activities I joined, and I can't imagine I had signed up for 1.1mb of them!

**Comment by amengsk** [comment]
if you only want the activities you joined there is already a filter for that in the backend, `&joined=true`, but it is not used in the frontend. dunno if it should be the default or not. perhaps we can add a tick box to the ics export dialog to let the user control that
