### ISSUE TITLE
Reputation system

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#260]
Feedback from Sweden:

A score created by adding the number of pick-ups carried out by a user and mutual evaluations.

Would require an additional evaluation feature, 
- either similar to the trust banana system used by foodsharing.de
- or a scale, where users can rate other users' quality and quantity of contributions e.g. from 1 to 5.

Feature request that heavily touches #89 in that it raises the question if hierarchies are needed or wanted at all inside the tool, because one of the possible solutions in mind is an extensive history tracking system, which is also meant to create trust - here via transparency.

**Comment by tiltec** [comment]
This is a very important feature and could definitely use some discussion. I also want to link our previous notes on this topic: https://yunity.atlassian.net/wiki/display/YUN/Trust+Module

**Comment by alangecker** [comment]
because of my ongoing discontent regarding the foodsharing.de hierarchy, I would really like to try out a different approach like duniter's [web of trust](https://duniter.org/en/introduction-a-la-toile-de-confiance/).

either way I guess it would make sense to implement "trust bananes" to collect already some data, which we could later use to simulate different solutions based on these relationships.

**Comment by tiltec** [comment]
Closing this in favour of #878
