### ISSUE TITLE
Stores teams and ideas for them

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#360]
improved concept for organizing teams - For a better understanding it helps to understand / know the foodsharing.de store system. 

## Experience from Foodsharing.de 
A team from a store can have maximum 3 "Store managers". 
based on experience different approaches can lead to different situations in a team:

## 1) Small team - members know each other
This is the easiest part. If the team is small and the members have some connection
to each other, it can be observed that more information is held transparent on the store wall
and difficulties are concern for more people. 

## 2) Big Team - members hardly know each other
This is the most difficult part to manage. As the team growes (due to either very "desirable" pickups or  due to the workload of the pickups). People know each other less and less. This usually leads to a shift into hierarchies. It comes more and more that the "store manager" is seen as the one  "who takes care of everything". This leads to a overload of work for the store manager.  More and more also complains of personal differences are put onto the store manager instead of the foodsaver feeling personally responsibility to find a adequate solution themselves. 

It was never intended that all workload should be put onto one person or that they would become like a "baby-sitter" for everything. 

Examples: 
- People neglect to look for a replacement if they can't (this can be very close to the pickup time).
- some people complain that they want to pickup more and more often often pointing to others "if they can , why can'T i?"
-> "He/she already has so many pickups in the team, can't he stop and leave the team, so that i can pick up?"
- or complain about what they get "the last time i went i only got one banana, and everyone else got two."
- or "he always takes the good stuff and i am left with the salad" 

you name it.

People like to talk to other people about whatever is going on and usually they like to turn to someone who "has the power" or is seen as an "administrative role". 

# **Solution Approach**
I would like to be able to define "Virtual" Roles(groups?) and describe them.
A minimum of 2 People should be in each role and maximum 3.  
(Theorically the foodsharing.de based permission system could be divided amongst these groups as well )

**Example for roles**

**Store manager** 
As a store manager you are hold up the communication between the team and the store. You remember on holidays to ask the store if the time for pickup changes and communicate it to the team. Talk to the store from time to time to see if they are happy or anything can be improved. If there is feedback from the team , that there is food in the bin - maybe you can talk to the store and ask about the reason , and if you can help out. 
Example for Administrative permission : Change store times, change store information
			    
**Team-Ear**
 "We are here to listen". If some foodsavers have a complaint or need someone to talk or have some ideas for the team. They could voice it here. Or Mentioning of problems with "what can i do with all the food". 
Example : What can i do with all my bread ? Where are organisations food can be brought to.Where are the next fair-share points?  
(maybe a cute little ear on the profile picture like the sleeping hat?)
administrative permission : Remove a person form a team. 
			

**Community Building**
As a community building team it would be nice if there can be opportunities for the team to
do something together. Bake cookies for the store on christmas. "Do stuff together". 
Example: Your store is a bakery ? Maybe have a breakfast once a year or once in 6 months. 
 Your store has vegetables ? Maybe cook something together. This could be an event either
 for the team or open for others in the community as well. 
							 
**Role-Balance**
You try to have a look that the number of pickups are equally distributed in the team. Why has someone 5 times more pickups than others? is that ok ?  Also if there is a request from outside the team to support an event with food they could see how it fits into the team and if food can be supplied. 
Administrative permission: (it's not in yunity but for foodsharing.de it would be approve a pickup, remove a person from a pickup)

**Team-Active**
You look after the setup of the team. Are enough active people in the team ? Maybe write a message to people who haven't being doing a pickup for a while, ask if they are still active and or if they need support. 
Administrative Permission : Open the team to look for people to help . Approve people to join.
				 							 
**How should these roles be assigned ?** 
Well the easiest part would be if foodsavers pick their role. But from experience i would be sceptical about it.
Another idea would be to have automatically assigned the first people who join to these roles till they are two in each. If someone doesn't want their role, they would have to look for a substitute. 				 							 

It would be nice if there would be an overview page or some visualisation of the groups assigned to the foodsavers.

# Advanced Thoughts 
**Restrictions**
It would be good if a foodsaver could only have x number roles accross different stores.Example :
I can only be "store manager" of 3 stores. I can only be Role-balance for x stores.
If a foodsaver is in x stores he has to have a least ONE role . 
Example: A foodsaver is in 5 stores as foodsaver - he should be able to have at least one role in one of these 5 stores. 

**Advanced features**
I would want to write to the team of roles (group chat?)
I would want to pick a person from that role and talk with them(personal chat).
The team itself should have a private possibility to talk about topics (forum?) and to have a history of what was discussed, so if members change it can be transparent what happenend. 

This might seem like a lot but this could make clearer what tasks a team needs and that people are more aware that they can be involved more. Right now everything falls back onto the store manager resulting in an overload.

**Comment by djahnie** [comment]
Lots of good ideas for the case that we _do_ implement store teams, thanks @Sliverriver!

Today @fstaiwan said that he'd like to have store teams like the ones on foodsharing.de. There are certain benefits as well as disadvantages in having those.
Stefan's main reasons for demanding store teams are the following:
- He wants to outsource management of the legal agreements to the store coordinators. (He wants to stick to paper solutions and is fine with people signing one agreement per store.)
- He wants to be able to open and close store teams and to have a feature that shows if a store team is looking for more foodsavers or not.
- In completely open teams everything works following a 'first come first serve' principle, which can be frustrating for slower users and make them leave again, so he'd like to have some control mechanisms.

Some arguments against store teams à la foodsharing.de:
- Inactive members can clutter the store team.
- People can block access to a store, make it their own and exert power over newcomers.
- You normally don't have access to all the info of a store before joining its team.

**Comment by djahnie** [comment]
From my POV I think it would be a shame to close the stores off from the wider community, but I still see the problems. 
I don't know how else to counter the greedy foodsavers than to try to get more cooperations actually. I'd try to have more community events and get more people to contact stores so that the problem of too less pick-up slots sorts itself out.

I think it could be nice to have something like a tag system: when you take the tag of a store you are added to a chatgroup and receive urgent news (as soon as there _is_ a chat, of course... 😉). The tags could be activated by default, so that you know, what's going on, when you first join.
OR admins can set which stores should give their tags to new users automatically. This would also give the possibility to see a list of people who subscribed to a store, which means, that you have something like a store team - you only cannot close it... 😉 

I also think that having store coordinators is a good idea. I also like the super nuanced approach Kristijan painted above, but I somehow feel that implementing these kinds of things would be too prescriptive. (A modular rights management kit is still my favourite, but I guess that won't happen very soon...^^) But store coordinators are a role that could also come with certain rights.
- Should they be the only ones, who can edit store details?
- Should they be the only ones, who can send out messages to the store chat?
- Should they simply be displayed prominently in the store view, so that users know who to turn to in case of problems or questions?

**Comment by Sliverriver** [comment]
to prevent the greed there is the "karma-system" that berlin is using. basically you get points for less attractive pickups or chores (cleaning fair -share-points) but therefore you gain the privilege to do a pickup at more desireable stores. and because you can choos how you want to contribute to the community by  many tasks that are managed through stores you have more choice. it helped them quite a lot.

**Comment by nicksellen** [comment]
> to prevent the greed there is the "karma-system" that berlin is using
how is it implemented?

**Comment by djahnie** [comment]
It is not, @nicksellen. Afaik on of the BOTs of Friedrichshain made some kind of plugin, that extracts the info of who did which pick-ups and aligned it with predefined point values. The point values are reassessed regularly and reflect the desirability of a store. This is then put down in some kind of table and each month an automatically generated summary goes out to every foodsaver, who did a pick-up in the district. Still, I guess most of the work is done manually (like excluding foodsavers from stores or adding them), also the reassessment is quite a hassle and there is _a lot_ of discussion and discontent as well...
But the idea in general could be worth keeping in mind...

**Comment by nicksellen** [comment]
@djahnie ah interesting, good to know. That's more the kind of direction I like for a couple of reasons:
1. they were able to actually _implement_ their own solution to the problem (could be a usecase for a having a good API)
2. using algorithms to solve problems that are very difficult for people to do manually (ok, sounds like there is still some aspect of manual effort here)

**Comment by Sliverriver** [comment]
it's not a plugin - it is a seperate program. (windows .exe)
you have to be store manager in the stores you want to evaluate. 
it's not using any API- it's basically using the "pick-up-history" and scraping that information . Using the html calls of the url as entry point and processing the result. 
you configure the stores and configure which pickup times get how many points (+/-). 
The result is a table of selected stores and the foodsavers who did a pickup during the period you specified. 
they don't give out the summary  - they would inform the "least" performers that they need to improve their rating. 
![karma](https://user-images.githubusercontent.com/2359021/29993188-faaa3e4e-8faf-11e7-8781-b606daeee99f.jpg)
(taken from https://foodsharing.de/?page=fairteiler&bid=19&sub=ft&id=563)
Alas the software is illegal because the user didn't give permission that his information is shared with other programms that is not the plattform, and that personal information is processed automatically. 
This led to a bigger topic - that the data privacy agreement for the website is out of date. This is an ongoing discussion.
The situation escalated quite in Munic. Despite some districts of berlin have been using that system for more then half a year successfully.
And of course it rattled some cages because then people can find out who has been only going to "good stoes" while other stores have been struggling, or other chores have been done by the same people.

**Comment by tiltec** [comment]
Just for sake of completeness and a bit off-topic: the foodsharing e.V. forbids the use of the software based on data privacy laws:

> BotschafterInnen
> Liebe Botschafter/innen,
> 
> ich wende mich auf diesem Wege in einer sehr ernsten Angelegenheit an alle Botschafter/innen und bitte Euch um Mithilfe.
> 
> In München ist im Juni diesen Jahres auf einem foodsharing-Treffen bekannt geworden, dass dort eine Software eingesetzt worden ist, um die Abholhistorien von Foodsaver/innen auslesen und mit einem Punktesystem (Karmapunkte) bewerten zu können. Dies ist wohl in der Absicht geschehen, dass Abholen "gerechter" organisieren zu können. Daraufhin haben sich Foodsaver/innen beim Landesbeauftragten für Datenschutz und Informationsfreiheit in NRW beschwert. Dieser hat nun mit der Untersuchung des Vorfalls begonnen und uns zur lückenlosen Aufklärung aufgefordert. Der foodsharing e.V. mit Sitz in Köln ist Inhaber und Betreiber der Webseite foodsharing.de und ist daher auch für den Datenschutz auf dieser Seite verantwortlich. Die Software ist weder vom Verein entwickelt worden, noch hat dieser jemals eine Erlaubnis erteilt diese einsetzen zu dürfen. Wir nehmen Datenschutz sehr ernst und werden alles in unserer Macht stehende tun, um weiteren Datenmissbrauch zu unterbinden. Das Auslesen und Bewerten der Abholhistorie ist nach unseren jetzigen Datenschutzbestimmungen nicht erlaubt. Wer es dennoch macht, eignet sich widerrechtlich Daten an. Dabei spielt es keine Rolle, ob diese Daten mit der Hand oder per Software ausgelesen werden. Natürlich können Betriebsverantwortliche in Ihren Betrieben die Abholhistorie einsehen, wie auch die Botschafter/innen. Diese Form der Dokumentation ist unbedingt notwendig, sonst könnte man beispielsweise im Falle einer Rückrufaktion von gespendeten Lebensmitteln nicht mehr zurückverfolgen, wer wann wo im Namen von foodsharing Lebensmittel abgeholt und weitergegeben hat. Aus der notwendigen Möglichkeit für Betriebsverantwortliche und auch Botschafter/innen diese Daten einsehen zu können, leitet sich nicht die Erlaubnis ab, diese auslesen, werten, speichern oder sonst wie nutzen zu dürfen.
> Da ich darüber informiert worden bin, dass diese Software zumindest noch in einer weiteren Stadt zum Einsatz kommt bzw. gekommen ist, muss ich den Einsatz dieser Software zum Auslesen und Bewerten von foodsharing-Daten untersagen: Die Software darf ab sofort nicht mehr benutzt werden. Die mit ihr erhobenen Daten müssen unverzüglich gelöscht bzw. vernichtet werden.
> 
> Wer die Software nach meiner Bekanntmachung dennoch nutzt oder die Abholhistorie dennoch anderweitig auswertet, begeht Datenmissbrauch! Solltet Ihr von Personen wissen, die diese Software nutzen, sprecht sie bitte an und macht sie auf das Problem aufmerksam. Es geht nicht um Denunziation, sondern darum die foodsharing-Webseite vor Datenmissbrauch zu schützen, damit ihr Betrieb nicht gefährdet wird. Daher auch meine Bitte an Euch grundsätzlich mit allen Daten, die Ihr einsehen könnt, absolut vertraulich umzugehen.
> Der Vorstand des foodsharing e.V. nimmt den Vorfall in München zum Anlass, die Datenschutzbestimmungen einer gründlichen Prüfung durch eine hierauf spezialisierte Anwaltskanzlei zu unterziehen. Dies wird einige Zeit in Anspruch nehmen. Von den daraus resultierenden Maßnahmen werdet Ihr selbstverständlich informiert.
> 
> Mit besten Grüßen,
> 
> Frank Bowinkelmann

You can try to get a good English translation here: https://www.deepl.com/translator

**Comment by tiltec** [comment]
This discussion quickly boils down to the very reasons why people save food:

1. to get good food for free
2. to prevent it from being thrown away
3. to give it to others

I think most people are really motivated by (1) and this causes a lot of problems that are hard to solve via software.

Imagine a cooperation where foodsavers fight against each other to get pick-up slots? What if we tell the stores that people _really want_ the food and they should try harder to sell it?

Imagine a cooperation where there's only spoiled food and nobody wants to pick it up? What if we just tell the stores that they do a good enough job at selling the good food and stop the cooperation? (Maybe they could do better storage management though)

The parts where foodsharing really shines are cooperations where there's a lot of good food that the store can't or doesn't want to sell anymore. That needs motivated people to pick up the food and distribute it among others, because it's too much to eat all alone.

**Comment by Sliverriver** [comment]
If ppl really would care about food waste or have a more self-less approach they would engage more then just pickkng up from "good" stores- which mostly serves themself. In the start of foodsharing there were more of those idealists and hippies who put more effort into these topics. As it is now, most of the idealists where shut down and what was once a communty grassroots movement is turning into self serving. 

The software could probably made legal(thats what some believe) if the data privacy agreement would allow it. everyone can just call up the landestadenschutzbeauftragten- there are nice and really helpfull to talk to. Depending on how you ask there might have been a way.

**Comment by tiltec** [comment]
I'll collect some needs here why people would want store teams. There could also be alternative solutions for them, like roles for stores.

- "I want to know who (generally) picks up food at a store, to ask for help and to have a sense of community"
- "This one store requires a special liability waiver from foodsavers"
- "Foodsavers need a special introduction before pickup up at a store"
- "The store owner wants nobody to know that he's cooperating, so we need to limit all information to as few people as possible"
- "I want to prevent certain people from picking up at this store because they did something wrong in the past"

Reasons to choose an alternative store team architecture than foodsharing.de include:

- "The store manager is not accepting me into this store because he wants to keep all food for himself and his friends"
- "I don't know if I can or want to pick up food at this store, because I don't know when the times are or what kind of food it usually gives away"

**Comment by nicco11a** [comment]
There are a lot of features you want, but a combination of all of them would be very complex for smaller groups so I think a need for a matrix where functions can be turned on or off depending on the size and challenges of the group in question so a complex tool would be too cumbersome for them to use. I also think functions requested needs to be prioritized so when the discussion of features settle down there is a need to vote for a list of functions that are going to be prioritized.

The point in regard to privacy laws can be a bit tricky due to different countries do not have the same laws in this area, but there are a lot of data that can be processed externally without needing to worry about privacy since most of the data is not private. For example to publish the number of pickups per week and put that in to proportion of volunteers without publishing there names, but I agree the line is rather thin. Perhaps opening for statistical plugins that can be added per group rather then encouraging the use of external programs where sensitive data may be stored in plain text and leak for example. There could be a group of volunteers who have the education to review the data from those plugins to ensure privacy concerns are handled properly. 

I still see a need for API functionality to publish how much food is collected on the different groups websites etc. Our possible user-case is that we have requested the list of all business in our town that are registered for handling food products and another list of how much some of those business (we are working on getting a more complete list) throw (about 1000 tons where one store alone managed to throw 175 tons per year) and we may want to correlate that data with the number of places we pickup at to show how we matter, yet how much is left to do. We could even go down to separate parts of the town to show our impact there and color the map of the city accordingly to enlighten people on the scale of the problem in there area. Without a external API all the data would need to be on Karrot and that would not make sense, but rather a lot of performance issues for the Karrot backend.

**Comment by djahnie** [comment]
This was an informative talk but very far away from any implementations. User feedback showed that store subsciptions (#986) would be sufficient and that store walls (#985) would be useful.
