### ISSUE TITLE
Minimal implementation of admin roles

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#550]
With @tiltec and @djahnie we discussed the admin role features that would be needed for implementing #324.

#356 discusses the wider topic of additional roles and is still relevant for the near future.

For #324 all that is needed is some set of users within the whole group that are able to edit the legal agreement. We realised we don't need to restrict other actions yet (e.g. ability to add stores).

In the future we would like to implement more non-hierarchical methods of managing admins but it is more realistic to start with a simple system.

We discussed whether having admins in a group should be optional or not, and realised if it was optional then it would be difficult to turn it on again in the future: if nobody is an admin, who has permission to enable admins? (this would be the case for existing groups, or new groups that initially selected not to have admins).

One option would be to have an owner of the group (by default the original creator, but could be reassigned) - but then we have just added an extra level of hierarchy and not solved anything.

Based on thoughts above we came up with the following concept:
1. each group must have at least one admin
2. if a group does not have an admin, then the oldest member of the group is promoted to admin (to comply with point 1)
3. only admins can edit the legal agreement
3. only admins can create other admins
4. only admins can remove other admins (they can remove the original admin of the group as all admins have equal powers)

This should allow us to implement the smallest possible admin system that allows us to continue with #324, whilst also leaving the future open to more admin-specific roles, and to build more mechanisms to create and remove admins.

**Comment by djahnie** [comment]
Tiny clarification in case someone misunderstood:
The _oldest_ member is the one who joined first. Age doesn't make any difference here... 😉

**Comment by Sliverriver** [comment]
i am starting to feel uncomfortable with the word "admin" probably because of many bad hierarchie examples missuse of power from foodsharing and facebook groups.

isn't it more like you have a feature - and you assign people to this feature. and not having a role that has 234234 features. 

or you have feature 1,2,3 and make a virtual role a that has feature 1 and a role b that has feature 1 and 2. and you assign the user to the role. 

that is also something that got a bit to much on foodsharing. like you have the orgateam(role admin) and every "admin" function was put into that role. which made it less flexible to give one function to person without giving them all access. 

How can we assign "powerfull" features (features that give power over other users) and prevent the missuse like on fs.de ? 
is it "if you gain a privilege you lose another?" for example if i can ban a user from the group i am not allowed to do pickups ? just brainstorming to give an idea.

**Comment by Sliverriver** [comment]
oh another thing is, having a legal agreement might require the user to have a valid address or sth. like that. (i don't know the exact law / legal binding), but remember sth. like that from fs.de

**Comment by nicksellen** [comment]
I agree, and don't think we actually need to call it "admin" in the software, but something more specific to the actual purpose we are addressing right now.

The role in question that we need is people that can modify the legal agreement, so it might be we could let that happen if users have the role "legal".

In general though, so far the feeling has been that we would like to leave it up to individual groups to decide how to organise themselves, but lean towards (and provide feature for) non-hierarchical approaches.

I've sketched out some implementation ideas in https://github.com/yunity/foodsaving-backend/issues/353 - and for that idea, it would just have _some role name_ that we add to the users group membership:

```
[user] <-- [membership roles=(role1,role2,role3)] --> [group]
```

**Comment by nicksellen** [comment]
> oh another thing is, having a legal agreement might require the user to have a valid address or sth. like that. (i don't know the exact law / legal binding), but remember sth. like that from fs.de

Maybe it should be more general than _legal agreement_ then (esp as we don't know the laws in all the countries), and just be "terms of use" (role=terms, or maybe role=agreement) kind of thing (for a given group). And maybe they can set the text for the agreement and also the title of it (e.g. "Legal Agreement", or "Terms of use" or "Community Guidelines" - we would lose the multi language aspect there though, unless we just supported a standard set of agreement _types_)

**Comment by tiltec** [comment]
> And maybe they can set the text for the agreement and also the title of it

Yes, that's what the legal agreement proposal is about: #324 
The name "legal agreement" wouldn't show up to the user like this.

Maybe an appropriate description would be: "terms you have to accept before you can join the group"?
And it can set by either anyone in the group or someone with the role "can-modify-terms".

This issue is about how to actually set roles in a group, coming from a group where everybody has all rights. Basically "bootstrapping group roles".

**Comment by Sliverriver** [comment]
i would like to take a step back -

how do we now if it is anything "legal" or binding" 

it could be a text like "You accept me as your lord and master and must do as i say". or
"if you accept this then you own me a cake! you willingly agree to this condition! " 

It can never be evaluated if whatever text people are writing is legally appropriate or even valid. 

So it is the featuer of a "welcome message that you either agree or decline"- declining making it unable for the user to join the group. 

that would be the feature description. 

Whatever the content is the user decides, but whoever is running the tool doesn't take any legal ownership / responsibility of the content of that message. and you could name it "friendship agreement, or "legal agreement" or whatever name you want or your imageniry lawyer tells you to.
 
maybe it would be usefull to avoid terms like "legally binding","terms of service", etc. that sound highly official and approved of some legal entity or including any kind of responsibility from the site owner.

**Comment by tiltec** [comment]
I copied your comment and my proposal into #324

**Comment by djahnie** [comment]
These are older thoughts, which led to newer thoughts. So these can be archived to not be distracting.
