### ISSUE TITLE
More features for group wall / improve conversations

### ISSUE THREAD

**Issue by D0nPiano** [yunity/karrot-frontend#610]
Starting with conversations & feedback for finished pickups, it'd make sense to implement a wall from now on. This would be a mixture of history, chat, and pickup-feedback.

Items I would include:
- **wallPost** (chat messages)
- **wallJoined** people who joined the group
- **wallPickup** when you did a pickup (with a button to give feedback, if not done so already)
- **wallFeedback** feedback for pickups

I think this could be a nice way of having all relevant information in one single place.

### Design Ideas
![screenshot from 2017-09-05 10-20-49](https://user-images.githubusercontent.com/16825880/30052176-f1b7f2d2-9224-11e7-9338-e1b001a4a08e.png)

![20170905_102200](https://user-images.githubusercontent.com/16825880/30052256-330c3cca-9225-11e7-82f1-beaf5a6a22c6.jpg)

...please don't mind my drawing skills :wink:

**Comment by nicksellen** [comment]
Yup, great idea to combine them into a feed. I was just looking at a pull request conversation tab, and that has all the useful things on it. Although those are top -> bottom, instead of bottom -> top (like a wall normally is).

A few questions it opens up too:
* what should do the combining of items:
  * frontend
  * backend
  * insert messages into the conversation for each thing that should be shown - this approach is my initial inclination, so it keeps the frontend/api simple (also the conversations is the only model that has the concept of updates being pushed over the websocket - although we can push more updates in the future)
* comment threads - it puts more need to have comments on conversation mesages (aka threads...) as you don't normally reply to a wall post with another wall post... (especially if there are other message types in there - although having said that, it's exactly what you do on a github pull request conversation thread, it's just a simple linear thing)
* how does this fit with the ideas in the other thread re chat vs wall style display (sorry, don't have it to hand, and have to turn off computer now!)

**Comment by Sliverriver** [comment]
i don't understand this issue , -most information referenced can be found in the history tab view .

**Comment by D0nPiano** [comment]
@nicksellen 
> Although those are top -> bottom, instead of bottom -> top (like a wall normally is).
..the messages are already ordered the other way round in the current chat UI proposal #597 (if that's what you meant)

I like the idea of adding messages in the conversation. Maybe we could have a "message-type" var for each message? So that they can still look differently in our frontend and stay translatable? Or we add an option to the history endpoint to also return the messages of the group-conversation and pickup-feedback (shouldn't pickup feedback be a history entry anyways?)

> comment threads

Comments would of course be even better, but I think for now it'd also make sense with what we have already (conversation + joins + feedback + your pickups)

> how does this fit with the ideas in the other thread re chat vs wall style display

From what I read in #583, it seems to go along with the idea of a wall quite well.

@Sliverriver 
My intention is to combine all relevant information in one place. Pickup-feedback doesn't have a spot yet where you could read through the feedback other people gave (except for `group/xxx/give-feedback`, but thats not really a good place in my opinion), and the conversations also need somewhere to go.
And since the history endpoint is so overloaded with people joining and leaving pickups and doing other things, I'd like to make it more prominent when new people arrived in a group.
I think the 4 points mentioned above (+ joining future pickups, which is hard to add to a chronological wall) are really the most important status-aspects of our tool. On the other hand, history seems more like a protocoll to me and should in my opinion be used more like an admin-tool in the future.

**Comment by tiltec** [comment]
**On history vs wall**

I agree with Lars, I like to think of the "history" as a complete log of everything that happened. It needs complex filters in order to be useful.
The "wall" is the information that users are mostly interested in, a selection of the history. It should have no filter parameters. Additionally, it has _actions_: you can create posts on the wall, probably edit them, comment on them.

**Wall as conversation**

I think adding a message type to conversations is a good idea. Then we push all relevant information into conversations and "wall" shows the group conversation. We can extend the concept to stores as well.

The question is: what is _relevant_ information? The "wall" content is the same for all users, so we can't make it user-specific.

Group wall content:
- users joining the group
- stores being added
- people posting on the wall
- upcoming pick-up where nobody has signed up so far (with join action)

Store wall content:
- feedback to pick-ups
- new pick-up dates
- people posting on the wall
- upcoming pick-up where nobody has signed up so far (with join action)

**Thoughts about sharing messages between conversations**

The content "upcoming pick-up where nobody has signed up so far" could make sense in the store wall too, but it doesn't seem to make much sense to send it twice. Can we already introduce the concept of _sharing_ messages? e.g. group wall would contain a reference to the store wall post.

**Comment threads**

Comparing it with Github issues: it has short-lived, top-to-bottom style conversations where comments are simply appended.
Group and store walls are long-lived and thus the _most recent message first_ style seems better. But it needs comments pretty soon.
Slack threads are an interesting model. Thread messages are normal messages, but they have a "thread_id" field. The client takes care of the proper displaying them.

Wow, a lot of words...

**Comment by nicksellen** [comment]
> Can we already introduce the concept of sharing messages? e.g. group wall would contain a reference to the store wall post.

I would not. Will get complicated very quickly. I think some duplication of content is fine here.

The facebook model seems much more like posts are independent things that get pulled into various feeds in various sort orders depending on magic algorithm - but our conversations are more like strict chronological things tied to a specific thing, which makes more sense to me for a _working_ tool like ours compared to a casual social tool like facebook.

I think the challenge for us is to get a clear concept of what a conversation entry is compared to an activity entry. Could be, something happens, then:
- we add an entry to the conversation AND to the history/activity independently
- writing an activity/history entry triggers a conversation entry to be made
- history/activity entries can be directly referenced in the conversation

Slightly separately the [slack attachments](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20message%20http%3A%2F%2Fslack.com%22%2C%22attachments%22%3A%5B%7B%22text%22%3A%22And%20here%E2%80%99s%20an%20attachment!%22%7D%5D%7D) approach seems quite nice, which includes types for links, buttons, etc...

**Comment by tiltec** [comment]
We currently have WallPosts, the rest should be discussed further and added at a later time.

**Comment by nicksellen** [comment]
Probably things that could be done here:
- [ ] add "type" (or similar) to conversation message entries (default is text, others might be markdown..., history/activity or something)
- [ ] render them in the frontend different
- [ ] add reactions!
- [ ] add comments (ooh er, gets complicated, I *think* they need to be their own conversation so we can track read/notifications correctly)

**Comment by tiltec** [comment]
I feel like we should plan the wall concept better. There was an idea to extend the wall in #741 with a list of all pickups that have open slots.
 
These "upcoming pickup alarms" are quite different from the other features proposed in the wall. The alarms stay until they are done (e.g. pickup done, all slots full, at least one slot filled), while the proposed wall features are mostly historic events (e.g. messages, who joined/left the group)

I think we should call the historic events the "feed" (in contrast to history, which shows all events), then we should have some "alarms" that consist of upcoming events of interest to the user (empty pickups, joined pickups).

**Comment by tiltec** [comment]
I enabled markdown for wall messages (also retroactively), but didn't introduce other messages types yet.

**Comment by djahnie** [comment]
Currently the wall conversation shows only people's messages. The upcoming pickups, as well as feedback to give, is displayed above. If we want the wall to become more like a news feed / dash board kind of thing we need to figure out how to go about it:
- How to treat the data; are all wall posts conversation items?
- How to display the different categories?
- Probably much more...^^

**Comment by tiltec** [comment]
The group wall seems to be the main location for notifications and group conversation, so we should be careful to keep it relevant to users. 

If there's more information to display, it would be better to split them into separate categories, to be shown on different pages:

- notifications: system-generated text, events that should have high priority to the user, need to be marked as read
- activity: system-generated text and user messages, all latest events to scroll through, limited to most 30 most recent entries
- conversation messages: only written by humans

**Comment by djahnie** [comment]
If we separate notifications and conversation into different pages, then we don't have a dashboard, or is activity meant to be the dashboard? Could also be okay to not have one though, I'm mainly pointing it out... 

Just to get more clarity on what you mean exactly with the three categories you mentioned, @tiltec, is it somewhat like this?:
- conversation: the group wall
- notifications: e.g. upcoming pickups I have signed up for, upcoming empty pickups
- activity: pickups done, feedbacks given, stores created, but user messages as well? Isn't this a weird, partly duplication of content from the conversation? I'm doubtful about the usefulness of this page actually. Or did I get it wrong?

**Comment by tiltec** [comment]
There was the idea of creating a dashboard that spans all groups the user is part of. In the meantime, I would close this issue and read back when we start working on the dashboard.
