### ISSUE TITLE
Add pickup feedback UI

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#639]
Pickup feedback is implemented in the backend. There are also some frontend components available. But no UI for adding feedback.

Perhaps a good place to put it for now is on the main group page at the top (where it shows upcoming pickups), or perhaps in a notification-style thing in the top right?

See https://github.com/yunity/karrot-frontend/issues/159 for broader discussion

**Comment by D0nPiano** [comment]
Since the quesion of user feedback arose again lately, what is our current status?

1. There is a first draft of a feedback-creation form on https://dev.karrot.world/#/group/1/feedback
2. There is a discussion on Notifications / bells:
  2.1 Website Notifications #577 that was closed due to:
  2.2 General discussion on Notifications #257
3. We had a dev feedback UI in angular #605 

**Plans**
So what exactly are our plans? From a UI point, I would
- [ ] Improve feedback creation form (1.)
  - [ ] make it more responsive
  - [ ] make it more form-like (add create button etc.)
- [ ] Add Website notification for possibility to give feedback (related to 2.1)
  - [ ] either as bells in topbar (with facebook-like list)
  - [ ] or as notification on group page (like empty & your pickups)
- [ ] think of a way to display feedback for user, store and group

I could probably start on those pretty soon, but don't really have time / motivation for the store related stuff. Would one of you guys be willing to help me out there? :grimacing: 

**Quesions**
- Does a bells thing make sense from our current backend implementation? Still didn't read into the store logic too much to tell
- Is there an update on the notification endpoint for the api?
- Is the feedback amound for a user / store / group already available backend wise?

**Comment by tiltec** [comment]
I can help with the vuex things and also the backend stuff :) Backend might take a bit longer, depending on the requirements. Maybe we go for a basic implementation without notifications for now, like the one I did in the angular frontend, to get some opinions from actual users.

I would start with the possibility to see the feedback, and then work back to give the feedback.

Maybe something like this?
- A page that lists all feedback per store and per group (we can submit some feedback via API on dev.karrot.world)
- Extend the feedback creation form so that the user can select a pickup to give feedback to
- Put a button to the feedback creation form somewhere
- Deploy and get opinions from users :)

**Comment by djahnie** [comment]
I'm happy to see activity here! ^_^

The minimal proposal from @tiltec would make it possible that every user can give feedback to every pickup, right? So if everyone was to enter an amount if saved food it, what would happen? I guess calculating a mean or median makes sense here.

**Comment by tiltec** [comment]
Maybe the frontend can calculate some preliminary statistics on the feedback page, but I wouldn't say it's a required feature for the first implementation.
When we found a good way to calculate statistics, I would like to have the statistics calculation in the backend, so some selected statistics can be shown to unauthenticated or non-member users.

@D0nPiano 
Are you happy to work on the first two steps? Do you need help from my side? Would it help if I submit some feedback data into dev.karrot.world? On the other hand, you could also use storybook to design the pages, then I connect them to the vuex store.

> - A page that lists all feedback per store and per group (we can submit some feedback via API on dev.karrot.world)
> -Extend the feedback creation form so that the user can select a pickup to give feedback to

**Comment by D0nPiano** [comment]
Yes! I will try to get some work on it done in the next two weeks - and thanks for offering helping with the vuex stuff 🙂 I'll go for the storybook approach first. If that doesn't work out well, I'll try to create some feedback on dev.karrot.world or let you know.

**Comment by tiltec** [comment]
As follow-up to #803, here are some bits I would want to improve in the current UI draft:

- [ ] pickupFeedback form: highlight "other pickups" button more
- [ ] pickupFeedback form: show pending status on create button
- [ ] amountviewer: make number less jumpy when sliding, e.g. by always showing the decimal
- [ ] use editMixin for pickupFeedback form to also allow editing feedback (see isEditable attribute of feedback to check if editing is allowed)
- [ ] Rename 'you took home' -> 'how much food was saved on this pickup' based on feedback from Bruno in https://github.com/yunity/karrot-frontend/issues/159#issuecomment-328352706
- [ ] FeedbackItem: linkify user name and store name
- [ ] Show group sidenav when in feedback page
- [ ] Remove feedback tab in pickups, add feedback to sidebar instead; I think we shouldn't introduce yet another navigation concept; alternatively, 
- [ ] Add infinite scroll to feedback list to have proper pagination support
- [ ] feedbackList: show hint when there is no feedback yet
- [ ] Show FeedbackNotice in group/store feedback lists (maybe needs another component layer)
- [ ] perhaps change default ordering of feedback to sort by pickup date, not by feedback creation date
