### ISSUE TITLE
Improve handling of changed pickup settings when saving series

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#797]
This is a possible bug, that I tried in different groups in dev and production. When I change the additional information field with a new text in a series of pickups and save it, the pickups that have already someone signed up to do not change. This is how you can test:

- Create a series of pickups, add a text to additional information for the whole series
- Join one of more pickups
- Go back and edit the series of pickups and change the text in additional information, then save
- Every pickup should be updated with the new text, except for those where a user joined

Updating the individual pickup worked for me.

**Comment by tiltec** [comment]
Thanks for the report, that's related to #611 
I will copy your comment there.

**Comment by tiltec** [comment]
Ah, I get what you mean! That's intentional, after people joined the pickup it won't get updated by the series anymore.

Do you think we should change it? Or just document it better?

**Comment by tiltec** [comment]
Currently we have these actions on pickups:

- modify comment
- modify time
- delete

If a series gets deleted, usually it will also affect the pickups, except in these cases:

- when the pickup has a collector
- when the attribute has been changed in the pickup itself (see #611 for a change request regarding to this, it's not resolved yet)

**Comment by tiltec** [comment]
Possible next steps:

- add a button to the pickup edit window: "reset to series default" (#611)
- **or:** add a checkbox when saving series: "override changed pickup settings"
- **or:** add a modal on saving series: "this series contains pickups with changed settings, do you want to override?"

- add a list to series delete: "these pickups will not get deleted because people already joined them. please notify the collectors in the pickup chats about the cancellation."

**Comment by tiltec** [comment]
As other problems related to recurring pickups came up, I propose some bigger changes that might also affect this issue: https://community.foodsaving.world/t/how-to-better-handle-changes-to-recurring-pickups/174
