### ISSUE TITLE
Long-lived conversation feature (forum or wall with comments)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#846]
As discussed today with @D0nPiano and @brunomc, a feature for long-lived conversations could be a nice addition in the future. 

We thought of two different options:

- A forum with thread title and answers, sorted by most recent answer, maybe categorized (think phpBB or discourse)
- Wall in which posts can be commented (and maybe comments can be commented too). Posts with recent answers would bubble up again to top maybe

I wouldn't want to implement both and each option comes with tradeoffs. Needs to identify them and decide for one.

**Comment by djahnie** [comment]
I think I prefer the threading option as it seems lighter. Maybe we could add the possibility to add a title to every post? Because if I ask a question and expect answers I know that my post will be commented and thus deserves a title.

**Comment by tiltec** [comment]
I wouldn't add a title, inspired by facebook and Slack. The first post can be very short to act as a title. Maybe we also add formatting capabilities to let the user highlight the first line of the first post if it should act as title.

**Comment by djahnie** [comment]
Ah yes right formatting! I took that as granted but just realized that it actually isn't... 😅 
Then I'm happier with it already. Still, facebook orders the threads in posts on a higher level and Slack has multiple channels as well. Do you imagine having a higher level sorting by allowing posts on the group wall, in a store, in a pickup, on a profile and maybe even more? Because if we _only_ have the one wall that is supposed to fulfill the communicative function of a forum for the whole group, I think it's not enough and will only get messy with threads.

**Comment by tiltec** [comment]
I didn't get any complaint yet that the wall is too spammy, I would wait until this happens before I take action.

**Comment by alterisa** [comment]
Hi there!
Im Isa from Austria (why are we writing in english?) anyway Im in Barcelona now and together with a group of motivated people we are building up a foodsharing community. There are existing plattforms but they arent really used. 
The 2nd meeting will open the discussion about: what do we want, how will we organise ourselfes,...maybe we will define some subgroups,... so I was wondering if the forum option is something that can be implemented allready or if it will take more time? 
Sorry cant code;-( 
I would love to have a forum implemented in karrot otherwise I dont think the platform will be atractive to use.

I was proposing a mumble call between karrot users and developers for next week. Would love to give feedback and hear about other experiences.

**Comment by tiltec** [comment]
As communication becomes a main karrot feature, this would be helpful! @nicksellen already had some ideas how to implement threads using our existing conversation feature, so this could happen in the half a year or so...
