### ISSUE TITLE
Add a field for public group contact

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#898]
Right now we have one field that holds a 'text you see before joining the group'. Theoretically it's enough, since people can write every piece of intormation in there, but in reality we often end up with password-protected groups that don't show any way of contacting them (e.g. Food Saving Lund)
It's very much possible, that they simply forget and that a field asking for a contact can change that.

So I'd like to split the 'text you see before joining the group' into two text boxes:
- The first for generic 'public group information'
- The second for a 'publicly visible group contact'

What do yout think? Starter task or product question? :wink:

**Comment by tiltec** [comment]
I think it's related to #894 as it improves the way how people join a group. But #894 goes much further, so it will take a while.
This issue could be implemented in short time, and it could help already. So I'd put it as starter tasks. Remove the label if you think otherwise ;)

I would call the field `contact information` and make it much smaller than the public group information to make the intention clear.

**Comment by tiltec** [comment]
With the new group application process and removal of the password feature, this might become less important.
