### ISSUE TITLE
Improve design of new group gallery map

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#956]
Thanks @D0nPiano for bringing back the group map! :tada: :smile: :dancer: 
There's just some bits I think could be better:

- The group list should be collapsed by default.
- The orange warning box should be on the right next to the group list, so that it is always visible.
- When effecting a successful search in the collapsed group list it should automatically decollapse and show the search results. With one result it does (and even centers the map to the location of the found group, nice! :+1: ) but with multiple results nothing happens.
- When effecting an unsuccessful search it should decollapse as well and show a message that no group matching the criteria could be found.

_on mobile_
- The group list should be collapsed by default.
- The orange warning box is trickier here... hm... Maybe we put it underneath the search bar in both versions? Dunno if that's cool... hm...
- The rest is the same as above, but in general everything looks better here! I guess you made it primarily for the mobile view, huh? :wink:

**Comment by D0nPiano** [comment]
No Problem :slightly_smiling_face: 

> The orange warning box should be on the right next to the group list, so that it is always visible.

Do you mean above the map on the right side of the screen? But yeah, I guess it makes sense to put it somewhere else.

And yeah, actually I didn't think about the search too much yet. But both of your requests make sense. Will change it accordingly.

> The rest is the same as above, but in general everything looks better here! I guess you made it primarily for the mobile view, huh? wink

Haha, and funny that you say that. Actually I made it for desktop first and wanted to have it exactly the same on mobile, but it had some really wired behavior with the fixed map & scrollable groups, wherefore it now looks so different on mobile / desktop.

My primary objective was to have a very large map on both devices, so that we could eventually add Fair-Share-Points or Food-baskets to the same concept of map. A bit like https://www.kartevonmorgen.org/#/?center=50.939,6.938&zoom=13.00

**Comment by tiltec** [comment]
It's sometimes impossible to press the "join" button:

![image](https://user-images.githubusercontent.com/4410802/37257988-2c358e12-2571-11e8-94c0-16eabae31382.png)

(karrot logo is just marked by accident)

I think the footer overlays it. When I hover over it, it doesn't show the hand and it doesn't react when I click on it.

**Comment by tiltec** [comment]
I have the feeling all points are either solved or obsolete.
