### ISSUE TITLE
Redirect to personal profile after changing it

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#968]
When submitting changes on one's personal profile right now the user stays on the personal settings page. It would be much more intuitive to get redirected to the profile to see the changes one made.

**Comment by neuroleptic** [comment]
@djahnie I am very interested in working on this!

**Comment by djahnie** [comment]
Awesome, @neuroleptic, go for it! :+1: :smiley:

**Comment by sarvanideekshitula** [comment]
I want to work on this

**Comment by neuroleptic** [comment]
@sarvanideekshitula I already finished this. Just waiting for the code review.

**Comment by mr-kojo** [comment]
My suggestion would be to display an alert message, similar to the one shown when the password or email address is changed.

**Comment by neuroleptic** [comment]
@mr-kojo I'll implement those changes.

**Comment by tiltec** [comment]
I found it nice to get redirected back to my profile page after changing my user details. Maybe we should collect actual user feedback though.
Maybe @djahnie knows if any user mentioned something related?

**Comment by djahnie** [comment]
I only know that it's nice to see _something_. If nothing happens users are unsure if their changes have been effected or not. This could definitely be achieved with an alert as well.
I think @mr-kojo's point is valid because there are multiple 'save' buttons. But if we don't have the redirect I'd maybe put a button down below that explicitly takes you back to your profile.

**Comment by trmendes** [comment]
I went check what happen when I save my profile after change it and I'm redirected to the profile page.

I agree with @tiltec that it would be more useful to stay at the profile page instead because I might need to click at another save button since the settings is devided in groups.

It might look broken if I:

* change my profile picture 
* change my description
* click at the "save button" from the description settings group 
* Be redirected to the profile page 
* I still see my profile picture there

So I would vote for some visual alert every time you click save like @mr-kojo sujested.

@neuroleptic Do you still working on it?

What is the current status of this issue? Still need some work?

**Comment by alekpentchev** [comment]
Is somebody working on this issue? What's the current status? I think I could help.

**Comment by tiltec** [comment]
@alekpentchev This issue still exists in production and it's not clear yet what a good solution to it is. So I'd be happy if you could have a look at it :)

**Comment by alekpentchev** [comment]
Cool, thank you. So I will try to resolve it.
