### ISSUE TITLE
Redirect to previous page after editing group description

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#999]
The group edit page can get opened from multiple places:

- Group overview page (in sidebar, the "three dots menu")
- Group description page (one of the action buttons)
- If no store or group location is set: group map in sidebar

**Comment by tiltec** [comment]
@mr-kojo I updated the list (searching for `name: 'groupEdit'`).

I guess the logic should be as follows:

- if there is a previous page, redirect to it
- if not, go to group home page (group wall)

With this, we don't need to know about all the places where groupEdit gets opened.

**Comment by pogopaule** [comment]
I'll work on this one

**Comment by tiltec** [comment]
I visited #999 again and came to the conclusion that `router.go(-1)` is not fitting here. Main problem is that it breaks "back button navigation".

This is how it should be:
1. user visits some group page and clicks edit
2. user makes a change and clicks save
3. user sees effects and wants to edit again, clicks back button
4. user is on group edit page again

#999 will break (4). Right now, (3) is slightly broken because the user may end up on a different page.

I see two solutions:
- keep track of the previous route and `router.push` it
- add more inline editing so that the user can stay on the same route while editing

**Comment by tiltec** [comment]
I'd close this because of high complexity and no user requests.
